first_name = input("Thank you for choosing us to make your ID! \n What is your first name? ")
print(f"Welcome {first_name.title()}! Please answer these basic informational questions to help us make your ID.")
last_name = input("Last name: ")
email = input("Email address: ")
phone = input("Phone number: ")
age = input("Age: ")
sex = input("Sex, M or F: ")
eye = input("Eye Color: ")
job = input("Job Title: ")
id = input("ID number: ")
train = input("Did you complete training? Yes or No: ")


print("Here is your ID!")
print("-" * 30)
print(f"{last_name.upper()}, {first_name.title()}")
print(job.title())
print(f"ID: {id} \n")
print(email.lower())
print(phone)
print(f"\nSex: {sex.upper():9}Eyes: {eye.title()}")
print(f"Age: {age:9}Training: {train.title()}")
print("-" * 30)